travis:
  secure:
    BINSTAR_TOKEN: Q2196tQmOOtyLLnMjZOpIpWfgosqb/qkyXeTLS0LOfmHGcKXWgfG8mXONX6zrML8nNP7c4Dxf72tVJfxOiOF6Twqbw3C8vEIvtqBLOC2bDBksjs2VeZnZGEWAxBc7SFQFYtxLQIFGkiJsqy3ETIqar45ohIxD3Ua6Ky6hYgFPL5K3ra+VqST1trOKZBNTBWNDpEzHu8TXEBq0cYHkfi87d1/Ro5kghEIvoi3zG1X9z1J/KZ67UIawtt6cGMK5zXAtsBo8Tjcb8YYnOQbQefHtBZM1WO9npJ5HLSDSRSVGwCNlAHhv1AiyjJJjWf/qsWsX/YPqhMVFM/hB9969P+h93UWOZIu3nrHybiW5iJTjkD22uV9/QQILaX9Tm6oUry2UBR8tsR4/LWtrYcfojiSHIvY7GYsLO6px/HFPHEZsWgozNpBt0Ra5KKbTJUAdzlH6Q5CFVxAa3II1StfmX3fwWXnqKGULkS7uZHIbb1rE9+5c0nKDika20jhzlWj3GlHSTwL4m9vaLV682ApdR+mNCjuvwfCGLL9aDs2L5rSD4wacr7Yy1KxQXHi8yi1hW52ZFq5Ai+mpG+xdaNUrZ1rD8j5gD1fp/FAmcOXKnVo30fWB3Zr6CcpKwdLrIYLVWH0VEUR03n5f0A9/IfBwH5t9tZGKZWmjow5ZRH9FzRe+L0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
